### ISSUE TITLE
EIA map

### ISSUE THREAD

**Issue by samanthacje** [Roytangrb/mapping-the-routes#19]
Some queries:
1. Is the map static? We used to be able to move it around
2. The bar chart used to be interactive too, can we still do it?
3. When we click on the bubble, it should show the case data like EIA's original map. Will that be done?
4. We can give you brighter colour codes for the bubbles
5. Can the map be full-width?
6. The copy of the counter - can you please use the one we sent?

**Comment by yasminzul** [comment]
Is it possible to use a map with pangolin routes on it?
