### ISSUE TITLE
Video background header

### ISSUE THREAD

**Issue by Roytangrb** [Roytangrb/mapping-the-routes#5]

**Comment by Roytangrb** [comment]
- [ ] dynamic load on desktop window size
- [ ] Add caption

**Comment by samanthacje** [comment]
Have uploaded mobile version of videos and photo (in case video doesn't load) https://drive.google.com/open?id=1JTZPxIFV6fTsgi2tYQbJevE7WRW4Z6BT

**Comment by samanthacje** [comment]
Please add the caption as a line below the video (it should only appear after you scroll past the video header)

**Comment by Roytangrb** [comment]
> Have uploaded mobile version of videos and photo (in case video doesn't load) https://drive.google.com/open?id=1JTZPxIFV6fTsgi2tYQbJevE7WRW4Z6BT

Header video for mobile and desktop updated, fallback posters updated

**Comment by Roytangrb** [comment]
> Please add the caption as a line below the video (it should only appear after you scroll past the video header)

* Caption added on desktop (device width > 480 px)
* The caption takes too many lines on mobile, set hidden on mobile

**Comment by samanthacje** [comment]
Play video audio

**Comment by Roytangrb** [comment]
> Play video audio

Updated
